# Generated by Django 4.0.1 on 2022-06-21 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_ingredients', models.JSONField(null=True)),
                ('recipe_directions', models.JSONField(null=True)),
                ('recipe_images', models.TextField(null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('difficulty', models.IntegerField(null=True)),
                ('recipe_intro', models.TextField(null=True)),
                ('prep_time', models.IntegerField(null=True)),
                ('cook_time', models.IntegerField(null=True)),
                ('meal_type', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
