# Generated by Django 4.0.5 on 2022-06-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cook_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='difficulty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meal_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='prep_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='recipe_intro',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='recipe_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='recipe_images',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
