# Generated by Django 4.0.1 on 2022-06-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='recipe_images',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
